environment:
  matrix:
    - STRAWBERRY_VERSION: 5.28.0.1
    - STRAWBERRY_VERSION: 5.24.0.1

skip_tags: true
cache:
install:
  - cinst strawberryperl --version %STRAWBERRY_VERSION%
  - refreshenv
  - where perl
  - FOR /F %%I IN ('perl -MConfig -e "print $Config{version};"') DO SET STRAWBERRY_CONFIG_VERSION=%%I
  - echo Installed %STRAWBERRY_VERSION% got %STRAWBERRY_CONFIG_VERSION%
  - set BP=c:\strawberry
  - set PP=%BP%\perl
  - path %SystemRoot%\system32;%PP%\site\bin;%PP%\vendor\bin;%PP%\bin;%BP%\c\bin
  - FOR /F %%I IN ('perl -MConfig -e "print $Config{version};"') DO SET STRAWBERRY_CONFIG_VERSION=%%I
  - echo 22 Installed %STRAWBERRY_VERSION% got %STRAWBERRY_CONFIG_VERSION%
  - chcp 65001 && cpanm CPANPLUS::Dist::PAR
build_script:
  - perl setconfig.pl
  - chcp 65001 && cpanp i         Function-Parameters MetaCPAN-Client CPANPLUS-Dist-PAR PAR-Repository
  - perl rundeps.pl Function-Parameters MetaCPAN-Client CPANPLUS-Dist-PAR PAR-Repository
  - copy *.pl PARs\runtime
  - parrepo create -r PARs\build\build
  - dir /b "%USERPROFILE%\.cpanplus"
  - parrepo inject -r PARS\build\build --file "%USERPROFILE%\.cpanplus\%STRAWBERRY_CONFIG_VERSION%\dist\PAR\*.par"
  - cpanp o >outdated.txt
  - type outdated.txt
artifacts:
  - path: PARs\build
    name: pars_build
    type: zip
  - path: PARs\runtime
    name: pars_runtime
    type: zip
